export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_COMPLETED = 'FETCH_USER_COMPLETED'
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED'
export const SHOW_SINGLE_USER = 'SHOW_SINGLE_USER'